/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafica;

import Codigo.Creacion_bbdd;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author basti
 */
public class modificarproducto extends javax.swing.JFrame {

    /**
     * Creates new form modificarproducto
     */
    Creacion_bbdd cb;
    
    public modificarproducto() {
        this.setResizable(false);
        initComponents();
        ImageIcon yalerojo = new ImageIcon (modificarproducto.class.getResource("/Imagenes/yalerojo.png"));
        this.setIconImage(yalerojo.getImage());
        this.setTitle("BODEGAS SSAB");
        setLocationRelativeTo(null);
        cb = new Creacion_bbdd();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        txt_idcat = new javax.swing.JTextField();
        txt_idsec = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblseccion = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblcategoria = new javax.swing.JTable();
        btn_vercat = new javax.swing.JButton();
        btn_versec = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_modpro = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_cod = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblproductos = new javax.swing.JTable();
        btn_salir2 = new javax.swing.JButton();
        btn_verpro = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btn_ingreso = new javax.swing.JButton();
        campo_categoria = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btn_ingreso2 = new javax.swing.JButton();
        campo_pasillo = new javax.swing.JTextField();
        campo_rack = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txtcate = new javax.swing.JTextField();
        btn_el_cat = new javax.swing.JButton();
        ver_cat = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txtsecc = new javax.swing.JTextField();
        ver_sec = new javax.swing.JButton();
        btn_el_sec = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblseccion2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblcategoria2 = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtidsec = new javax.swing.JTextField();
        txtpasec = new javax.swing.JTextField();
        txtrasec = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ver_idcata = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        ver_catid = new javax.swing.JButton();
        txtidcat = new javax.swing.JTextField();
        txtnmcat = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html>Ingrese ID de seccion:</html>");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ver categoria:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Codigo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("<html>Ingrese ID de producto a modificar:</html>");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("<html>Ingrese ID de categoria:</html>");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 110, -1));
        jPanel1.add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 90, -1));
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, -1));
        jPanel1.add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 110, -1));
        jPanel1.add(txt_idcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 110, -1));
        jPanel1.add(txt_idsec, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 110, -1));

        tblseccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "PASILLO ", "RACK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblseccion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 220, 60));

        tblcategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "CATEGORIA_NOMBRE "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblcategoria);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 220, 60));

        btn_vercat.setText("VER");
        btn_vercat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vercatActionPerformed(evt);
            }
        });
        jPanel1.add(btn_vercat, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        btn_versec.setText("VER");
        btn_versec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_versecActionPerformed(evt);
            }
        });
        jPanel1.add(btn_versec, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Modificar productos");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ver seccion:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        btn_modpro.setText("Modificar");
        btn_modpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modproActionPerformed(evt);
            }
        });
        jPanel1.add(btn_modpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        jButton6.setText("Revisar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 70, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        jPanel1.add(txt_cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/yalerojo73.png"))); // NOI18N
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bt.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 380));

        jTabbedPane1.addTab("Modificar ", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Productos en bodega");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        tblproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "CODIGO", "NOMBRE", "CANTIDAD", "PASILLO", "CATEGORIA_NOMBRE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblproductos);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 560, 190));

        btn_salir2.setText("Salir");
        btn_salir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_salir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        btn_verpro.setText("Mostrar productos");
        btn_verpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verproActionPerformed(evt);
            }
        });
        jPanel2.add(btn_verpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/yalerojo73.png"))); // NOI18N
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bt.jpg"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 380));

        jTabbedPane1.addTab("Ver ", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("<html>Ingrese categoria nueva:</html>");
        jLabel14.setToolTipText("");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 130, -1));

        btn_ingreso.setText("Ingresar");
        btn_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresoActionPerformed(evt);
            }
        });
        jPanel3.add(btn_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        jPanel3.add(campo_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 120, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cajas2.png"))); // NOI18N
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cajas2.png"))); // NOI18N
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cajas2.png"))); // NOI18N
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cajas2.png"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cajas2.png"))); // NOI18N
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("<html>Ingrese seccion nueva:</html>");
        jLabel20.setToolTipText("");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 170, -1));

        btn_ingreso2.setText("Ingresar");
        btn_ingreso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingreso2ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_ingreso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 90, -1));
        jPanel3.add(campo_pasillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 120, -1));
        jPanel3.add(campo_rack, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 120, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Rack:");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Nombre:");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Pasillo:");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/yalerojo73.png"))); // NOI18N
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bt.jpg"))); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 380));

        jTabbedPane1.addTab("categoria o seccion", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("<html>Ingrese ID de seccion a eliminar:</html>");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, -1));
        jPanel4.add(txtcate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, -1));

        btn_el_cat.setText("Eliminar");
        btn_el_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_el_catActionPerformed(evt);
            }
        });
        jPanel4.add(btn_el_cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        ver_cat.setText("Ver");
        ver_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_catActionPerformed(evt);
            }
        });
        jPanel4.add(ver_cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Seccion:");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 80, -1));
        jPanel4.add(txtsecc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 110, -1));

        ver_sec.setText("Ver");
        ver_sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_secActionPerformed(evt);
            }
        });
        jPanel4.add(ver_sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        btn_el_sec.setText("Eliminar");
        btn_el_sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_el_secActionPerformed(evt);
            }
        });
        jPanel4.add(btn_el_sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        tblseccion2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "PASILLO", "RACK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblseccion2);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 260, 70));

        tblcategoria2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "CATEGORIA_NOMBRE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblcategoria2);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 260, 70));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("<html>Ingrese ID de categoria a eliminar:</html>");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Categoria:");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 150, -1));

        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/yalerojo73.png"))); // NOI18N
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bt.jpg"))); // NOI18N
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 380));

        jTabbedPane1.addTab("Eliminar categoria o seccion", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Modificar seccion");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Pasillo:");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("<html>Ingrese ID a modificar:</html>");
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Modificar categoria");
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Rack:");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Nombre:");
        jPanel5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));
        jPanel5.add(txtidsec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, -1));
        jPanel5.add(txtpasec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 100, -1));
        jPanel5.add(txtrasec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, -1));

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        ver_idcata.setText("Ver");
        ver_idcata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_idcataActionPerformed(evt);
            }
        });
        jPanel5.add(ver_idcata, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("<html>Ingrese ID a modificar:</html>");
        jPanel5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 130, -1));

        ver_catid.setText("Ver");
        ver_catid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_catidActionPerformed(evt);
            }
        });
        jPanel5.add(ver_catid, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));
        jPanel5.add(txtidcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 120, -1));
        jPanel5.add(txtnmcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 120, -1));

        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jPanel5.add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/yalerojo73.png"))); // NOI18N
        jPanel5.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bt.jpg"))); // NOI18N
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 380));

        jTabbedPane1.addTab("Modificar categoria o seccion", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_salir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salir2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (txt_codigo.getText().equals("")) {
            ImageIcon vacio = new ImageIcon (modificarproducto.class.getResource("/Imagenes/vacio.png"));
            JOptionPane.showMessageDialog(null, "El campo esta vacio!!","Mensaje",JOptionPane.DEFAULT_OPTION,vacio);
        }else{
        int codigo = Integer.parseInt(txt_codigo.getText());
        cb.VERPRODUC(codigo, tblseccion, txt_nombre, txt_cantidad, txt_idcat, txt_idsec,txt_cod);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        txt_nombre.setText("");
        txt_cantidad.setText("");
        txt_idcat.setText("");
        txt_idsec.setText("");
        txt_cod.setText("");
        txt_codigo.setText("");
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_versecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_versecActionPerformed
        cb.versec(tblseccion);
    }//GEN-LAST:event_btn_versecActionPerformed

    private void btn_vercatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vercatActionPerformed
        cb.vercat(tblcategoria);
    }//GEN-LAST:event_btn_vercatActionPerformed

    private void btn_modproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modproActionPerformed
        if (txt_nombre.getText().equals("")||txt_cantidad.getText().equals("")||txt_idcat.getText().equals("")||
                txt_idsec.getText().equals("")||txt_cod.getText().equals("")||txt_codigo.getText().equals("")) {
            ImageIcon vacio = new ImageIcon (modificarproducto.class.getResource("/Imagenes/vacio.png"));
            JOptionPane.showMessageDialog(null, "Hay campos vacios!!","Mensaje",JOptionPane.DEFAULT_OPTION,vacio);
        }else{
       
        String nombre = txt_nombre.getText();
        int id =Integer.parseInt(txt_codigo.getText());
        int codigo =Integer.parseInt(txt_cod.getText());
        int cantidad =Integer.parseInt(txt_cantidad.getText());
        int id_sec =Integer.parseInt(txt_idsec.getText());
        int id_cat =Integer.parseInt(txt_idcat.getText());
        
        cb.IDMODIFICARPRODUCTO(id, nombre, codigo, cantidad, id_sec, id_cat);
        txt_nombre.setText("");
        txt_cantidad.setText("");
        txt_idcat.setText("");
        txt_idsec.setText("");
        txt_cod.setText("");
        txt_codigo.setText("");
        }
    }//GEN-LAST:event_btn_modproActionPerformed

    private void btn_verproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verproActionPerformed
        cb.mostrarproductos(tblproductos);
    }//GEN-LAST:event_btn_verproActionPerformed

    private void btn_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresoActionPerformed

        if (campo_categoria.getText().equals("")) {
            ImageIcon vacio = new ImageIcon (modificarproducto.class.getResource("/Imagenes/vacio.png"));
            JOptionPane.showMessageDialog(null, "El campo esta vacio!!","Mensaje",JOptionPane.DEFAULT_OPTION,vacio);
        }else{
        String cat = campo_categoria.getText();
        cb.IDCategoria(cat); 
        }
    }//GEN-LAST:event_btn_ingresoActionPerformed

    private void btn_ingreso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingreso2ActionPerformed
        
        if (campo_pasillo.getText().equals("")||campo_rack.getText().equals("")) {
            ImageIcon vacio = new ImageIcon (modificarproducto.class.getResource("/Imagenes/vacio.png"));
            JOptionPane.showMessageDialog(null, "Hay campos vacios!!","Mensaje",JOptionPane.DEFAULT_OPTION,vacio);
        }else{
        String pas = campo_pasillo.getText();
        String rack = campo_rack.getText();
        cb.IDSeccion(pas, rack);
        }
    }//GEN-LAST:event_btn_ingreso2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ver_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_catActionPerformed
        cb.vercat2(tblcategoria2);
    }//GEN-LAST:event_ver_catActionPerformed

    private void ver_secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_secActionPerformed
        cb.versec2(tblseccion2);
    }//GEN-LAST:event_ver_secActionPerformed

    private void btn_el_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_el_catActionPerformed
        if (txtcate.getText().equals("")) {
            ImageIcon vacio = new ImageIcon (modificarproducto.class.getResource("/Imagenes/vacio.png"));
            JOptionPane.showMessageDialog(null, "El campo esta vacio!!","Mensaje",JOptionPane.DEFAULT_OPTION,vacio);
        }else{
            int id = Integer.parseInt(txtcate.getText());
        cb.delcat(id);
        txtcate.setText("");
        }
    }//GEN-LAST:event_btn_el_catActionPerformed

    private void btn_el_secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_el_secActionPerformed
        if (txtsecc.getText().equals("")) {
            ImageIcon vacio = new ImageIcon (modificarproducto.class.getResource("/Imagenes/vacio.png"));
            JOptionPane.showMessageDialog(null, "El campo esta vacio!!","Mensaje",JOptionPane.DEFAULT_OPTION,vacio);
        }else{
            int id = Integer.parseInt(txtsecc.getText());
        cb.delsec(id);
        txtsecc.setText("");
        }
    }//GEN-LAST:event_btn_el_secActionPerformed

    private void ver_catidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_catidActionPerformed
        
        if (txtidcat.getText().equals("")) {
            ImageIcon vacio = new ImageIcon (modificarproducto.class.getResource("/Imagenes/vacio.png"));
            JOptionPane.showMessageDialog(null, "El campo esta vacio!!","Mensaje",JOptionPane.DEFAULT_OPTION,vacio);
        }else{
            int id = Integer.parseInt(txtidcat.getText());
        cb.VERPORCAR(txtnmcat, id);
        }
    }//GEN-LAST:event_ver_catidActionPerformed

    private void ver_idcataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_idcataActionPerformed
                if (txtidsec.getText().equals("")) {
                    ImageIcon vacio = new ImageIcon (modificarproducto.class.getResource("/Imagenes/vacio.png"));
            JOptionPane.showMessageDialog(null, "El campo esta vacio!!","Mensaje",JOptionPane.DEFAULT_OPTION,vacio);
        }else{
            int id = Integer.parseInt(txtidsec.getText());
        cb.VERPORSEC(txtpasec, txtrasec, id);
        }
    }//GEN-LAST:event_ver_idcataActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        txtnmcat.setText("");
        txtidcat.setText("");
        txtpasec.setText("");
        txtrasec.setText("");
        txtidsec.setText("");
        
    }//GEN-LAST:event_limpiarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (txtpasec.getText().equals("")||txtrasec.getText().equals("")||txtidsec.getText().equals("")) {
            ImageIcon vacio = new ImageIcon (modificarproducto.class.getResource("/Imagenes/vacio.png"));
            JOptionPane.showMessageDialog(null, "Hay campos vacios!!","Mensaje",JOptionPane.DEFAULT_OPTION,vacio);
        }else{
            int id =Integer.parseInt(txtidsec.getText());
            String pasillo=txtpasec.getText();
            String rack=txtrasec.getText();
        cb.MODIFICARSECCION(id, pasillo, rack);
        txtpasec.setText("");
        txtrasec.setText("");
        txtidsec.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (txtidcat.getText().equals("")||txtnmcat.getText().equals("")) {
            ImageIcon vacio = new ImageIcon (modificarproducto.class.getResource("/Imagenes/vacio.png"));
            JOptionPane.showMessageDialog(null, "Hay campos vacios!!","Mensaje",JOptionPane.DEFAULT_OPTION,vacio);
        }else{
            int id =Integer.parseInt(txtidcat.getText());
            String nombre=txtnmcat.getText();
        cb.MODIFICARCATEGORIA(id, nombre);
        txtnmcat.setText("");
        txtidcat.setText("");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modificarproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modificarproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modificarproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modificarproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modificarproducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_el_cat;
    private javax.swing.JButton btn_el_sec;
    private javax.swing.JButton btn_ingreso;
    private javax.swing.JButton btn_ingreso2;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_modpro;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_salir2;
    private javax.swing.JButton btn_vercat;
    private javax.swing.JButton btn_verpro;
    private javax.swing.JButton btn_versec;
    private javax.swing.JTextField campo_categoria;
    private javax.swing.JTextField campo_pasillo;
    private javax.swing.JTextField campo_rack;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton limpiar;
    private javax.swing.JTable tblcategoria;
    private javax.swing.JTable tblcategoria2;
    private javax.swing.JTable tblproductos;
    private javax.swing.JTable tblseccion;
    private javax.swing.JTable tblseccion2;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_cod;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_idcat;
    private javax.swing.JTextField txt_idsec;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txtcate;
    private javax.swing.JTextField txtidcat;
    private javax.swing.JTextField txtidsec;
    private javax.swing.JTextField txtnmcat;
    private javax.swing.JTextField txtpasec;
    private javax.swing.JTextField txtrasec;
    private javax.swing.JTextField txtsecc;
    private javax.swing.JButton ver_cat;
    private javax.swing.JButton ver_catid;
    private javax.swing.JButton ver_idcata;
    private javax.swing.JButton ver_sec;
    // End of variables declaration//GEN-END:variables
}
