/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafica;

import Codigo.Creacion_bbdd;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/**
 *
 * @author basti
 */
public class nuevamod extends javax.swing.JFrame {

    /**
     * Creates new form nuevamod
     */
    Creacion_bbdd cb;
    public nuevamod() {
        initComponents();
        ImageIcon yalerojo = new ImageIcon (nuevamod.class.getResource("/Imagenes/yalerojo.png"));
        this.setIconImage(yalerojo.getImage());
        this.setTitle("BODEGAS SSAB");
        configurarRB();
        cb = new Creacion_bbdd();
    }
    public void configurarRB(){
        ButtonGroup botones = new ButtonGroup();
        
        botones.add(rb_mas);
        botones.add(rb_fe);
        botones.add(rb_ot);
        rb_ot.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campo_nombre = new javax.swing.JTextField();
        campo_apellido = new javax.swing.JTextField();
        campo_rut = new javax.swing.JTextField();
        campo_nmusuario = new javax.swing.JTextField();
        campo_contrasena = new javax.swing.JTextField();
        rb_mas = new javax.swing.JRadioButton();
        rb_fe = new javax.swing.JRadioButton();
        rb_ot = new javax.swing.JRadioButton();
        btn_modificar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        campo_id = new javax.swing.JTextField();
        ver_id = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_moduser = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        btn_mostar = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sexo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese id a modificar:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rut:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contraseña:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombre usuario:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));
        jPanel1.add(campo_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, -1));
        jPanel1.add(campo_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, -1));
        jPanel1.add(campo_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 90, -1));
        jPanel1.add(campo_nmusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 90, -1));
        jPanel1.add(campo_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 90, -1));

        rb_mas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb_mas.setForeground(new java.awt.Color(255, 255, 255));
        rb_mas.setText("Masculino");
        rb_mas.setContentAreaFilled(false);
        jPanel1.add(rb_mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        rb_fe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb_fe.setForeground(new java.awt.Color(255, 255, 255));
        rb_fe.setText("Femenino");
        rb_fe.setContentAreaFilled(false);
        jPanel1.add(rb_fe, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        rb_ot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb_ot.setForeground(new java.awt.Color(255, 255, 255));
        rb_ot.setText("Otro");
        rb_ot.setContentAreaFilled(false);
        jPanel1.add(rb_ot, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Modificar usuario:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        jPanel1.add(campo_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 90, -1));

        ver_id.setText("Ver");
        ver_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_idActionPerformed(evt);
            }
        });
        jPanel1.add(ver_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        tbl_moduser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "NOMBRE", "APELLIDO", "RUT", "SEXO", "NOMBRE_USUARIO", "CONTRASEÑA"
            }
        ));
        jScrollPane1.setViewportView(tbl_moduser);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 410, 50));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/yalerojo73.png"))); // NOI18N
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bt.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 390));

        jTabbedPane1.addTab("Modificar ususario", jPanel1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "APELLIDO", "RUT", "SEXO", "NOMBRE_USUARIO", "TIPO_USER"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblUsuario);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 640, 200));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Usuarios en sistema");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jPanel3.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, -1));

        btn_mostar.setText("Mostrar usuarios");
        btn_mostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_mostar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/yalerojo73.png"))); // NOI18N
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bt.jpg"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 390));

        jTabbedPane1.addTab("Ver usuarios", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed

                if (campo_contrasena.getText().equals("") || campo_nombre.getText().equals("") ||campo_apellido.getText().equals("") ||
            campo_rut.getText().equals("") || campo_nmusuario.getText().equals("") ) {
            ImageIcon vacio = new ImageIcon (nuevamod.class.getResource("/Imagenes/vacio.png"));
            JOptionPane.showMessageDialog(null, "Hay campos vacios!!","Mensaje",JOptionPane.DEFAULT_OPTION,vacio);
        }else{
            int id = Integer.parseInt(campo_id.getText());
            String contrasena = campo_contrasena.getText();
            String nombre = campo_nombre.getText();
            String apellido = campo_apellido.getText();
            String rut = campo_rut.getText();
           
            String nm_usuario = campo_nmusuario.getText();
            
            String m,f;
            if (rb_mas.isSelected()) {
                m="Masculino";
                cb.IDMODIFICAR(id, nombre, apellido, rut, m, nm_usuario, contrasena);
                campo_contrasena.setText("");
                campo_nombre.setText("");
                campo_apellido.setText("");
                campo_rut.setText("");
                campo_nmusuario.setText("");
            }else if(rb_fe.isSelected()){
                m="Femenino";
                cb.IDMODIFICAR(id, nombre, apellido, rut, m, nm_usuario, contrasena);
                campo_contrasena.setText("");
                campo_nombre.setText("");
                campo_apellido.setText("");
                campo_rut.setText("");
                campo_nmusuario.setText("");
            }else{
                m="Otro";
                cb.IDMODIFICAR(id, nombre, apellido, rut, m, nm_usuario, contrasena);
                campo_contrasena.setText("");
                campo_nombre.setText("");
                campo_apellido.setText("");
                campo_rut.setText("");
                campo_nmusuario.setText("");
            }
            
        }
        
        
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void ver_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_idActionPerformed
        if (campo_id.getText().equals("")) {
            ImageIcon vacio = new ImageIcon (nuevamod.class.getResource("/Imagenes/vacio.png"));
            JOptionPane.showMessageDialog(null, "El campo esta vacio!!","Mensaje",JOptionPane.DEFAULT_OPTION,vacio);
        }else{
        
        int id= Integer.parseInt(campo_id.getText());
        cb.MODUSERR(id, tbl_moduser, campo_nmusuario, campo_nombre, campo_apellido, campo_contrasena, campo_rut);
        }
    }//GEN-LAST:event_ver_idActionPerformed

    private void btn_mostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostarActionPerformed
        cb.mostrarUsuarios(tblUsuario);
    }//GEN-LAST:event_btn_mostarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevamod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevamod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevamod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevamod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevamod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_mostar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JTextField campo_apellido;
    private javax.swing.JTextField campo_contrasena;
    private javax.swing.JTextField campo_id;
    private javax.swing.JTextField campo_nmusuario;
    private javax.swing.JTextField campo_nombre;
    private javax.swing.JTextField campo_rut;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rb_fe;
    private javax.swing.JRadioButton rb_mas;
    private javax.swing.JRadioButton rb_ot;
    private javax.swing.JTable tblUsuario;
    private javax.swing.JTable tbl_moduser;
    private javax.swing.JButton ver_id;
    // End of variables declaration//GEN-END:variables
}
